spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_fitness_user_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
